name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: download
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          sudo apt update && sudo apt install -y yt-dlp
          yt-dlp --config-location config.txt
          if [ -n "$(git status --porcelain)" ]; then
            git add downloads/
            git commit -m "Add downloaded video"
            git push
          else
            echo "No changes to commit"
          fi
